In [251]:
#import things
import pandas as pd
# pd.set_option('max_columns', 200) mostra todas as colunas da tabela

In [252]:
#dataset
df = pd.read_csv('raw_data/addresses.csv')
df.info()
# df.shape ---> mostra quantas linhas e colunas tem a tabela

<class 'pandas.DataFrame'>
RangeIndex: 3998 entries, 0 to 3997
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            3998 non-null   int64
 1   customer_id   3998 non-null   int64
 2   address_type  3998 non-null   str
 3   postal_code   3998 non-null   str
 4   street        3998 non-null   str
 5   number        3998 non-null   int64
 6   complement    1647 non-null   str
 7   district      3998 non-null   str
 8   city          3998 non-null   str
 9   state         3998 non-null   str
 10  country       3998 non-null   str
 11  is_primary    3998 non-null   bool
dtypes: bool(1), int64(3), str(8)
memory usage: 347.6 KB

In [250]:
# Começar a limpar
df = df.set_index('id') # coloca a coluna id como index da tabela
# df.dtypes mostra o tipo de dados de cada coluna
df

,customer_id,address_type,postal_code,street,number,complement,district,city,state,country,is_primary
id,,,,,,,,,,,
1,1,billing,93032-645,Núcleo Macedo,13,NaN,Vila Aeroporto,Martins,SP,BR,True
2,1,secondary,06351-685,Via Cassiano,77,NaN,Vila Piratininga Venda Nova,Freitas de Campos,BA,BR,False
3,1,secondary,83799-005,Passarela Silveira,49,NaN,Delta,Monteiro,PA,BR,False
4,2,billing,34228562,Fazenda de Martins,83,Apto 225,Vila Real 1ª Seção,Caldeira,AL,BR,True
5,3,billing,37008942,Favela de da Cunha,4,Apto 704,Distrito Industrial Do Jatoba,da Conceição,SP,BR,True
...,...,...,...,...,...,...,...,...,...,...,...
3994,1998,billing,21418-047,Rodovia Nogueira,40,NaN,Vila Nova,Andrade,AM,BR,True
3995,1998,billing,27470540,Trevo de Moura,86,NaN,Apolonia,Sousa da Serra,AP,BR,False
3996,1999,billing,44647-976,Setor Dias,44,Apto 866,Nova Suíça,Fogaça,AL,BR,True
3997,1999,billing,84518185,Rodovia Azevedo,44,Apto 831,Esplanada,da Mata,AM,BR,False
3998,2000,billing,09578294,Viela de Borges,797,Apto 530,Vila Do Pombal,Moura da Serra,PB,BR,True

In [209]:
# encontrando missing values
df.isna().sum() # encontra todos os campos onde falta valor (no caso, encontra os valores NaN)

customer_id        0
address_type       0
postal_code        0
street             0
number             0
complement      2351
district           0
city               0
state              0
country            0
is_primary         0
dtype: int64

In [210]:
df.duplicated() # avalia se o registro é duplicado
# df.loc[df.duplicated()] mostra os registros duplicados se houver
# df.loc[df.duplicated(subset=['postal_code'])]

id
1       False
2       False
3       False
4       False
5       False
        ...
3994    False
3995    False
3996    False
3997    False
3998    False
Length: 3998, dtype: bool

In [ ]:
df.loc[df.duplicated(subset=['street'])] # identifica se valores de colunas específicas estão duplicados

,customer_id,address_type,postal_code,street,number,complement,district,city,state,country,is_primary
id,,,,,,,,,,,
83,41,billing,43167-859,Ladeira de da Luz,90,Apto 895,Vila Piratininga,Alves,DF,BR,True
122,59,billing,16570-794,Distrito Caldeira,330,NaN,Indaiá,Gonçalves,RO,BR,False
353,172,billing,58923036,Parque Macedo,88,NaN,Camponesa 1ª Seção,da Mata,SP,BR,True
382,187,billing,47412081,Aeroporto de Correia,48,Apto 825,Grajaú,Vieira,PI,BR,False
395,192,secondary,28854273,Ladeira de da Luz,379,NaN,Luxemburgo,Camargo do Amparo,RR,BR,False
...,...,...,...,...,...,...,...,...,...,...,...
3970,1984,billing,35814-918,Vereda de Casa Grande,73,.,Vila União,Fogaça de Sales,RO,BR,False
3973,1986,billing,17502-278,Viaduto Caldeira,7,NaN,Taquaril,Casa Grande de Goiás,MS,BR,True
3980,1989,billing,74225853,Pátio de da Costa,30,Apto 998,Nova Vista,Rodrigues,RO,BR,True
3982,1990,secondary,11434-383,Núcleo Alves,88,NaN,Vila Independencia 2ª Seção,da Rocha Paulista,PA,BR,False
3983,1990,secondary,17490-955,Vale Vargas,207,Apto 796,Vila Minaslandia,Costela da Serra,AP,BR,False

In [212]:
# tirar o hífen do CEP
cep = df['postal_code']
df['postal_code'] = cep.str.replace('-', '', regex=False) 
df['postal_code'].tail()

id
3994    21418047
3995    27470540
3996    44647976
3997    84518185
3998    09578294
Name: postal_code, dtype: str

In [213]:
# ruas = df[df['street'] == 'Ladeira de da Luz']
cidades = df.loc[df['state'] == 'SP', 'city'] # cidades por estado
cidades

id
1                    Martins
5               da Conceição
66                    Castro
102                       Sá
103                    Souza
                ...
3878        Pacheco Paulista
3933    das Neves das Flores
3964                  Duarte
3972                   Viana
3979      Costela das Flores
Name: city, Length: 148, dtype: str

In [242]:
# Tirar o 'de da' dos nomes das cidades
df.query("city.str.contains('de da')")
df = df.copy()
df['city'] = df['city'].str.replace('de da', 'da')
#df.query("city.str[0].str.islower() == True and state == 'SP'")
df

,customer_id,address_type,postal_code,street,number,complement,district,city,state,country,is_primary
id,,,,,,,,,,,
1,1,billing,93032645,Núcleo Macedo,13,NaN,Vila Aeroporto,Martins,SP,BR,True
2,1,secondary,06351685,Via Cassiano,77,NaN,Vila Piratininga Venda Nova,Freitas de Campos,BA,BR,False
3,1,secondary,83799005,Passarela Silveira,49,NaN,Delta,Monteiro,PA,BR,False
4,2,billing,34228562,Fazenda de Martins,83,Apto 225,Vila Real 1ª Seção,Caldeira,AL,BR,True
5,3,billing,37008942,Favela de da Cunha,4,Apto 704,Distrito Industrial Do Jatoba,da Conceição,SP,BR,True
...,...,...,...,...,...,...,...,...,...,...,...
3994,1998,billing,21418047,Rodovia Nogueira,40,NaN,Vila Nova,Andrade,AM,BR,True
3995,1998,billing,27470540,Trevo de Moura,86,NaN,Apolonia,Sousa da Serra,AP,BR,False
3996,1999,billing,44647976,Setor Dias,44,Apto 866,Nova Suíça,Fogaça,AL,BR,True
3997,1999,billing,84518185,Rodovia Azevedo,44,Apto 831,Esplanada,da Mata,AM,BR,False
3998,2000,billing,09578294,Viela de Borges,797,Apto 530,Vila Do Pombal,Moura da Serra,PB,BR,True

In [243]:
df.query("city.str[0].str.islower() == True and state == 'SP'")

,customer_id,address_type,postal_code,street,number,complement,district,city,state,country,is_primary
id,,,,,,,,,,,
5,3,billing,37008942,Favela de da Cunha,4,Apto 704,Distrito Industrial Do Jatoba,da Conceição,SP,BR,True
343,168,billing,58868102,Favela Gabriel Carvalho,726,NaN,Cdi Jatoba,da Mata do Amparo,SP,BR,True
353,172,billing,58923036,Parque Macedo,88,NaN,Camponesa 1ª Seção,da Mata,SP,BR,True
374,184,billing,14853331,Chácara Thomas Marques,555,Apto 129,Sion,da Rocha,SP,BR,True
410,200,billing,01481297,Vale Novais,940,NaN,Urca,da Cruz dos Dourados,SP,BR,False
514,252,billing,18172035,Trecho Gabrielly Fogaça,14,Apto 019,Bela Vitoria,da Rocha Grande,SP,BR,False
550,271,billing,97670254,Colônia Júlia Moraes,54,NaN,Minaslandia,da Paz da Praia,SP,BR,True
657,324,billing,33672115,Praia Rebeca Azevedo,90,NaN,Conjunto Celso Machado,da Rocha,SP,BR,True
904,451,secondary,79257852,Largo Cassiano,180,NaN,Vila Sesc,da Rocha,SP,BR,False
1033,520,billing,71042599,Aeroporto Santos,58,NaN,Conjunto Jatoba,da Mota,SP,BR,True
1053,530,billing,31625751,Área Almeida,76,Apto 857,Belvedere,da Costa Verde,SP,BR,True
1064,534,billing,75684978,Avenida Marcela Moreira,37,NaN,Vila Santo Antônio,da Conceição do Norte,SP,BR,False
1282,639,billing,70087775,Vale Aragão,4,Apto 226,Alto Vera Cruz,da Costa da Paz,SP,BR,True
1623,816,billing,53139783,Lago Maria Liz Garcia,49,Apto 777,Cidade Nova,das Neves,SP,BR,True
2336,1169,billing,70607714,Recanto de Gonçalves,42,Apto 691,Santa Helena,da Costa,SP,BR,False
2514,1259,billing,96540650,Distrito Costa,56,NaN,Vila São Rafael,da Rosa,SP,BR,True
2876,1436,secondary,73459986,Vale Ágatha Pacheco,192,Apto 858,Vila Trinta E Um De Março,da Mata,SP,BR,False
2912,1453,secondary,32999604,Estação Araújo,21,Apto 217,Vila Nova Gameleira 2ª Seção,da Mata,SP,BR,False
2951,1472,billing,60835233,Chácara de Peixoto,386,Apto 770,Cinquentenário,da Cunha de Novaes,SP,BR,False
3065,1526,secondary,67192012,Rodovia Ana Liz das Neves,8,NaN,Bela Vitoria,da Paz da Mata,SP,BR,False
3291,1647,billing,03356264,Via de Aragão,659,NaN,Lagoinha Leblon,da Rosa,SP,BR,True
3330,1668,billing,58525724,Distrito de Vargas,99,NaN,Pompéia,da Luz do Sul,SP,BR,True
3502,1754,billing,47340361,Rua de da Luz,7,Apto 148,Vila Copasa,da Mata das Pedras,SP,BR,False
3933,1967,billing,30022900,Praia de Macedo,77,Apto 555,Aparecida 7ª Seção,das Neves das Flores,SP,BR,True

In [245]:
#print(df['state'].unique())
df['city'] == 'Barbosa do Sul'

id
1       False
2       False
3       False
4       False
5       False
        ...
3994    False
3995    False
3996    False
3997    False
3998    False
Name: city, Length: 3998, dtype: bool